# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: BUILD BASELINE
on:
  schedule:
    - cron: '31 6 * * 1-5'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.10'
          architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run application
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        export LOCAL_HOST=True
        python src/build/service.py

    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run : |
        git config --global user.name 'SNOB ACTIONS'
        git config --global user.email 'snob.labwons@gmail.com'
        TIMESTAMP=$(date)
        git add .
        git commit -m "BUILD BASELINE on $TIMESTAMP"
        git push
